name: meshtastic_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# use 
# flutter pub outdated
# flutter pub upgrade 
version: 1.0.0+1

environment:
  # sdk: ">=2.11.0-213.0.dev <2.12.0" # for null safety test
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.00 <2.0.0"

dependencies:
  # auto_route: ^0.6.9  # could not resolve package uri Dec 2020 - try again later?
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  bloc: ^7.0.0
  dartz: 0.10.0-nullsafety.1  
  flutter_bloc: ^7.0.0
  flex_color_scheme: ^2.0.0
  # convex_bottom_bar: ^2.7.1+2
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  grouped_list: ^4.0.0-nullsafety.1
  injectable: ^1.2.2
  logging: '>=0.11.4 <2.0.0'
  #  see https://github.com/leisim/logger_flutter/issues/6  
  # and https://github.com/ewertonrp/logger_flutter
  # logger_flutter: '^0.7.1'
  # logger_flutter:
  #   git: https://github.com/ewertonrp/logger_flutter.git
  logger: ^1.0.0
  # recase: ^3.0.1
  protobuf: ^2.0.0      # flutter blue also uses
  shared_preferences: ^2.0.5
  # preferences: '^5.2.1'   // see https://pub.dev/packages/pref
  wakelock: ^0.5.0+2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  # auto_route_generator: ^0.6.10
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5   # was ^1.12.2, conflict with freezed
  freezed: ^0.12.7    #build runner dependency
  # json_serializable: ^3.3.0
  effective_dart: ^1.0.0
  pedantic: ^1.9.0
  very_good_analysis: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
